// Re-export Lucide icons with aliases to maintain existing imports
export {
  Sun as SunIcon,
  Moon as MoonIcon,
  ChevronDown as DownIcon,
  LogOut as LogoutIcon,
  Check as CheckIcon,
  EllipsisVertical as MenuDotsIcon,
  Search as MagnifyingGlassIcon,
  Folder as FolderIcon,
  FolderOpen as FolderOpenIcon,
  File as FileIcon,
  Settings as CogIcon,
  Zap as BoltIcon,
  Monitor as ComputerDesktopIcon,
  Star as StarIcon,
  Sparkles as SparklesIcon,
  X as XIcon,
  Repeat as UnoReverseIcon,
  Plus as PlusIcon,
  RefreshCw as ArrowPathIcon,
  Cpu as CpuChipIcon,
  Receipt as ReceiptIcon,
  TrendingDown as ArrowTrendingDownIcon,
  TrendingUp as ArrowTrendingUpIcon,
  Filter as FunnelIcon,
  Copy as DocumentDuplicateIcon,
} from 'lucide-vue-next'
